apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-agent
  namespace: learning
spec:
  selector:
    matchLabels: {app: node-agent}
  template:
    metadata:
      labels: {app: node-agent}
    spec:
      containers:
        - name: agent
          image: busybox:1.36
          command: ["sh", "-c", "while true; do echo node=$(cat /etc/hostname) time=$(date); sleep 30; done"]
          resources:
            requests: {cpu: 10m, memory: 8Mi}
            limits: {cpu: 50m, memory: 32Mi}
