apiVersion: v1
kind: Pod
metadata:
  name: resource-demo
  namespace: learning
spec:
  containers:
    - name: app
      image: nginx:1.27-alpine
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 300m
          memory: 128Mi
